In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Bhagyashri\archive.zip')
df.head()

,Index,batting_team,bowling_team,city,runs_left,balls_left,wickets,target_runs,cur_run_rate,req_run_rate,result
0,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.0,10.43697479,0
1,1,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.0,10.52542373,0
2,2,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.0,10.61538462,0
3,3,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.5,10.60344828,0
4,4,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.4,10.48695652,0

In [7]:
df

,Index,batting_team,bowling_team,city,runs_left,balls_left,wickets,target_runs,cur_run_rate,req_run_rate,result
0,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.000000,10.43697479,0
1,1,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.000000,10.52542373,0
2,2,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.000000,10.61538462,0
3,3,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.500000,10.60344828,0
4,4,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.400000,10.48695652,0
...,...,...,...,...,...,...,...,...,...,...,...
72408,72408,Chennai Super Kings,Mumbai Indians,Hyderabad,1,4,5,153,7.862069,1.5,0
72409,72409,Chennai Super Kings,Mumbai Indians,Hyderabad,-1,3,5,153,7.897436,-2,0
72410,72410,Chennai Super Kings,Mumbai Indians,Hyderabad,-2,2,4,153,7.881356,-6,0
72411,72411,Chennai Super Kings,Mumbai Indians,Hyderabad,-4,1,4,153,7.915966,-24,0
72412,72412,Chennai Super Kings,Mumbai Indians,Hyderabad,-4,0,3,153,7.850000,#NAME?,0

In [9]:
#Task 2 (Finding Unique Teams): Identify and extract the exact names of all unique IPL teams present in the dataset.

In [10]:
df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Delhi Daredevils',
       'Mumbai Indians', 'Kings XI Punjab', 'Kolkata Knight Riders',
       'Sunrisers Hyderabad', 'Rajasthan Royals', 'Chennai Super Kings',
       'Deccan Chargers', 'Delhi Capitals'], dtype=object)

In [11]:
#Task 3 (Team Performance Analysis): Calculate the number of matches played and won by each team across different cities.

In [12]:
city_analysis = df.groupby(['city', 'batting_team']).size().reset_index(name='matches_count')

In [13]:
city_analysis.head(10)

        city           batting_team  matches_count
0  Abu Dhabi       Delhi Daredevils             96
1  Abu Dhabi        Kings XI Punjab            118
2  Abu Dhabi  Kolkata Knight Riders            242
3  Abu Dhabi         Mumbai Indians            121
4  Abu Dhabi       Rajasthan Royals            199
5  Ahmedabad    Chennai Super Kings            123
6  Ahmedabad       Delhi Daredevils            233
7  Ahmedabad        Kings XI Punjab            121
8  Ahmedabad  Kolkata Knight Riders            246
9  Ahmedabad       Rajasthan Royals            578

In [14]:
#Task 4 (Chasing & Target Analytics): Analyze which teams successfully chased down the highest target runs.

In [15]:
chasing_data = df[df['result'] == 1]
top_chases = chasing_data.groupby('batting_team')['target_runs'].max().reset_index(name='highest_chase')

In [16]:
top_chases = top_chases.sort_values(by='highest_chase', ascending=False)
top_chases

                  batting_team  highest_chase
7             Rajasthan Royals            215
0          Chennai Super Kings            214
5        Kolkata Knight Riders            211
4              Kings XI Punjab            206
3             Delhi Daredevils            205
6               Mumbai Indians            205
8  Royal Challengers Bangalore            204
9          Sunrisers Hyderabad            204
2               Delhi Capitals            197
1              Deccan Chargers            185

In [17]:
#Task 5 (Run Rate & Spike Detection): Track how the run rate changes across different overs (1 to 20) and detect any scoring spikes.

In [18]:
over_analysis = df.groupby('balls_left')['cur_run_rate'].mean().reset_index()

In [19]:
over_analysis.head(10)

   balls_left  cur_run_rate
0          -2      7.568306
1          -1      8.085124
2           0      7.928838
3           1      7.960723
4           2      8.004057
5           3      7.996550
6           4      7.953929
7           5      8.007537
8           6      7.971027
9           7      7.958785